# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomePage.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomePage(object):
    def setupUi(self, HomePage):
        HomePage.setObjectName("HomePage")
        HomePage.resize(981, 755)
        HomePage.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(HomePage)
        self.centralwidget.setObjectName("centralwidget")
        self.label_AppName = QtWidgets.QLabel(self.centralwidget)
        self.label_AppName.setGeometry(QtCore.QRect(410, 20, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_AppName.setFont(font)
        self.label_AppName.setObjectName("label_AppName")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 60, 981, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 400, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(490, 440, 54, 12))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_Project1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Project1.setGeometry(QtCore.QRect(30, 130, 281, 251))
        self.label_Project1.setObjectName("label_Project1")
        self.label_Project2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Project2.setGeometry(QtCore.QRect(350, 130, 271, 251))
        self.label_Project2.setObjectName("label_Project2")
        self.label_Project3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Project3.setGeometry(QtCore.QRect(660, 130, 271, 251))
        self.label_Project3.setObjectName("label_Project3")
        self.label_User1 = QtWidgets.QLabel(self.centralwidget)
        self.label_User1.setGeometry(QtCore.QRect(20, 440, 281, 251))
        self.label_User1.setObjectName("label_User1")
        self.label_User2 = QtWidgets.QLabel(self.centralwidget)
        self.label_User2.setGeometry(QtCore.QRect(330, 430, 281, 251))
        self.label_User2.setObjectName("label_User2")
        self.label_User3 = QtWidgets.QLabel(self.centralwidget)
        self.label_User3.setGeometry(QtCore.QRect(640, 430, 281, 251))
        self.label_User3.setObjectName("label_User3")
        HomePage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HomePage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Login = QtWidgets.QMenu(self.menubar)
        self.menu_Login.setObjectName("menu_Login")
        self.menuSearch_Users_Projects = QtWidgets.QMenu(self.menubar)
        self.menuSearch_Users_Projects.setObjectName("menuSearch_Users_Projects")
        HomePage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HomePage)
        self.statusbar.setObjectName("statusbar")
        HomePage.setStatusBar(self.statusbar)
        self.action_Login = QtWidgets.QAction(HomePage)
        self.action_Login.setStatusTip("")
        self.action_Login.setObjectName("action_Login")
        self.action_Registration = QtWidgets.QAction(HomePage)
        self.action_Registration.setObjectName("action_Registration")
        self.actionUser_Search = QtWidgets.QAction(HomePage)
        self.actionUser_Search.setObjectName("actionUser_Search")
        self.actionProject_Search = QtWidgets.QAction(HomePage)
        self.actionProject_Search.setObjectName("actionProject_Search")
        self.menu_Login.addAction(self.action_Login)
        self.menu_Login.addAction(self.action_Registration)
        self.menuSearch_Users_Projects.addAction(self.actionUser_Search)
        self.menuSearch_Users_Projects.addAction(self.actionProject_Search)
        self.menubar.addAction(self.menu_Login.menuAction())
        self.menubar.addAction(self.menuSearch_Users_Projects.menuAction())

        self.retranslateUi(HomePage)
        QtCore.QMetaObject.connectSlotsByName(HomePage)

    def retranslateUi(self, HomePage):
        _translate = QtCore.QCoreApplication.translate
        HomePage.setWindowTitle(_translate("HomePage", "MainWindow"))
        self.label_AppName.setText(_translate("HomePage", "TeamUp"))
        self.label.setText(_translate("HomePage", "Top Projects:"))
        self.label_2.setText(_translate("HomePage", "Top User:"))
        self.label_Project1.setText(_translate("HomePage", "Project 1"))
        self.label_Project2.setText(_translate("HomePage", "Project 2"))
        self.label_Project3.setText(_translate("HomePage", "Project 3"))
        self.label_User1.setText(_translate("HomePage", "OU"))
        self.label_User2.setText(_translate("HomePage", "VIP"))
        self.label_User3.setText(_translate("HomePage", "SU"))
        self.menu_Login.setTitle(_translate("HomePage", "Log in"))
        self.menuSearch_Users_Projects.setTitle(_translate("HomePage", "Search"))
        self.action_Login.setText(_translate("HomePage", "Log in as returning users"))
        self.action_Registration.setText(_translate("HomePage", "New user registration"))
        self.actionUser_Search.setText(_translate("HomePage", "User Search"))
        self.actionProject_Search.setText(_translate("HomePage", "Project Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomePage = QtWidgets.QMainWindow()
    ui = Ui_HomePage()
    ui.setupUi(HomePage)
    HomePage.show()
    sys.exit(app.exec_())
