from PyQt5 import QtCore, QtGui, QtWidgets
from ProfilePage import Ui_profilePage
import pandas as pd

# HomePage2
class Ui_HomePage2(object):
    def logout(self):
        HomePage2.close()

    def openProfileWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_profilePage()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, HomePage2):
        HomePage2.setObjectName("HomePage2")
        HomePage2.resize(980, 710)
        self.centralwidget = QtWidgets.QWidget(HomePage2)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Logout = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Logout.setGeometry(QtCore.QRect(880, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_Logout.setFont(font)
        self.pushButton_Logout.setObjectName("pushButton_Logout")

        self.pushButton_Logout.clicked.connect(self.logout)

        self.pushButton_Groups = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Groups.setGeometry(QtCore.QRect(790, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_Groups.setFont(font)
        self.pushButton_Groups.setObjectName("pushButton_Groups")
        self.pushButton_Inbox = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Inbox.setGeometry(QtCore.QRect(700, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_Inbox.setFont(font)
        self.pushButton_Inbox.setObjectName("pushButton_Inbox")
        self.pushButton_Profile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Profile.setGeometry(QtCore.QRect(610, 20, 81, 31))

        self.pushButton_Profile.clicked.connect(self.openProfileWindow)

        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_Profile.setFont(font)
        self.pushButton_Profile.setObjectName("pushButton_Profile")
        self.label_AppName = QtWidgets.QLabel(self.centralwidget)
        self.label_AppName.setGeometry(QtCore.QRect(410, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_AppName.setFont(font)
        self.label_AppName.setObjectName("label_AppName")
        self.pushButton_Search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Search.setGeometry(QtCore.QRect(200, 20, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_Search.setFont(font)
        self.pushButton_Search.setObjectName("pushButton_Search")
        self.textEdit_Search = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Search.setGeometry(QtCore.QRect(10, 20, 181, 31))
        self.textEdit_Search.setObjectName("textEdit_Search")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 60, 981, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(490, 440, 54, 12))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_User3ProjectDescription = QtWidgets.QLabel(self.centralwidget)
        self.label_User3ProjectDescription.setGeometry(QtCore.QRect(670, 490, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_User3ProjectDescription.setFont(font)
        self.label_User3ProjectDescription.setObjectName("label_User3ProjectDescription")
        self.label_User1Stat = QtWidgets.QLabel(self.centralwidget)
        self.label_User1Stat.setGeometry(QtCore.QRect(20, 570, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_User1Stat.setFont(font)
        self.label_User1Stat.setObjectName("label_User1Stat")
        self.label_User2ID = QtWidgets.QLabel(self.centralwidget)
        self.label_User2ID.setGeometry(QtCore.QRect(350, 450, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_User2ID.setFont(font)
        self.label_User2ID.setObjectName("label_User2ID")
        self.label_TopUsers = QtWidgets.QLabel(self.centralwidget)
        self.label_TopUsers.setGeometry(QtCore.QRect(20, 400, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_TopUsers.setFont(font)
        self.label_TopUsers.setObjectName("label_TopUsers")
        self.label_TopProjects = QtWidgets.QLabel(self.centralwidget)
        self.label_TopProjects.setGeometry(QtCore.QRect(20, 80, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_TopProjects.setFont(font)
        self.label_TopProjects.setObjectName("label_TopProjects")
        self.label_User1Name = QtWidgets.QLabel(self.centralwidget)
        self.label_User1Name.setGeometry(QtCore.QRect(20, 480, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_User1Name.setFont(font)
        self.label_User1Name.setObjectName("label_User1Name")
        self.label_Project2Descrip = QtWidgets.QLabel(self.centralwidget)
        self.label_Project2Descrip.setGeometry(QtCore.QRect(350, 170, 291, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_Project2Descrip.setFont(font)
        self.label_Project2Descrip.setObjectName("label_Project2Descrip")
        self.label_User1ID = QtWidgets.QLabel(self.centralwidget)
        self.label_User1ID.setGeometry(QtCore.QRect(20, 450, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_User1ID.setFont(font)
        self.label_User1ID.setObjectName("label_User1ID")
        self.label_Project2Member = QtWidgets.QLabel(self.centralwidget)
        self.label_Project2Member.setGeometry(QtCore.QRect(350, 250, 241, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_Project2Member.setFont(font)
        self.label_Project2Member.setObjectName("label_Project2Member")
        self.label_Project1Title = QtWidgets.QLabel(self.centralwidget)
        self.label_Project1Title.setGeometry(QtCore.QRect(30, 160, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_Project1Title.setFont(font)
        self.label_Project1Title.setObjectName("label_Project1Title")
        self.label_User3Score = QtWidgets.QLabel(self.centralwidget)
        self.label_User3Score.setGeometry(QtCore.QRect(670, 610, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_User3Score.setFont(font)
        self.label_User3Score.setObjectName("label_User3Score")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(810, 440, 54, 12))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_User2Stat = QtWidgets.QLabel(self.centralwidget)
        self.label_User2Stat.setGeometry(QtCore.QRect(350, 570, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_User2Stat.setFont(font)
        self.label_User2Stat.setObjectName("label_User2Stat")
        self.label_User3ID = QtWidgets.QLabel(self.centralwidget)
        self.label_User3ID.setGeometry(QtCore.QRect(670, 450, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_User3ID.setFont(font)
        self.label_User3ID.setObjectName("label_User3ID")
        self.label_User2ProjectDescription = QtWidgets.QLabel(self.centralwidget)
        self.label_User2ProjectDescription.setGeometry(QtCore.QRect(350, 490, 311, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_User2ProjectDescription.setFont(font)
        self.label_User2ProjectDescription.setObjectName("label_User2ProjectDescription")
        self.label_user1Score = QtWidgets.QLabel(self.centralwidget)
        self.label_user1Score.setGeometry(QtCore.QRect(20, 610, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_user1Score.setFont(font)
        self.label_user1Score.setObjectName("label_user1Score")
        self.label_Project2Title = QtWidgets.QLabel(self.centralwidget)
        self.label_Project2Title.setGeometry(QtCore.QRect(350, 160, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_Project2Title.setFont(font)
        self.label_Project2Title.setObjectName("label_Project2Title")
        self.label_User3Stat = QtWidgets.QLabel(self.centralwidget)
        self.label_User3Stat.setGeometry(QtCore.QRect(670, 570, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_User3Stat.setFont(font)
        self.label_User3Stat.setObjectName("label_User3Stat")
        self.label_User2Name = QtWidgets.QLabel(self.centralwidget)
        self.label_User2Name.setGeometry(QtCore.QRect(350, 480, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_User2Name.setFont(font)
        self.label_User2Name.setObjectName("label_User2Name")
        self.label_Project1Member = QtWidgets.QLabel(self.centralwidget)
        self.label_Project1Member.setGeometry(QtCore.QRect(30, 250, 241, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_Project1Member.setFont(font)
        self.label_Project1Member.setObjectName("label_Project1Member")
        self.label_Project3Member = QtWidgets.QLabel(self.centralwidget)
        self.label_Project3Member.setGeometry(QtCore.QRect(660, 250, 241, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_Project3Member.setFont(font)
        self.label_Project3Member.setObjectName("label_Project3Member")
        self.label_Project3Descrip = QtWidgets.QLabel(self.centralwidget)
        self.label_Project3Descrip.setGeometry(QtCore.QRect(660, 170, 311, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_Project3Descrip.setFont(font)
        self.label_Project3Descrip.setObjectName("label_Project3Descrip")
        self.label_Project3ID = QtWidgets.QLabel(self.centralwidget)
        self.label_Project3ID.setGeometry(QtCore.QRect(660, 130, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_Project3ID.setFont(font)
        self.label_Project3ID.setObjectName("label_Project3ID")
        self.label_User2Score = QtWidgets.QLabel(self.centralwidget)
        self.label_User2Score.setGeometry(QtCore.QRect(350, 610, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_User2Score.setFont(font)
        self.label_User2Score.setObjectName("label_User2Score")
        self.label_Project1ID = QtWidgets.QLabel(self.centralwidget)
        self.label_Project1ID.setGeometry(QtCore.QRect(30, 130, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_Project1ID.setFont(font)
        self.label_Project1ID.setObjectName("label_Project1ID")
        self.label_Project3Title = QtWidgets.QLabel(self.centralwidget)
        self.label_Project3Title.setGeometry(QtCore.QRect(660, 160, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_Project3Title.setFont(font)
        self.label_Project3Title.setObjectName("label_Project3Title")
        self.label_User1ProjectDescription = QtWidgets.QLabel(self.centralwidget)
        self.label_User1ProjectDescription.setGeometry(QtCore.QRect(20, 490, 311, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_User1ProjectDescription.setFont(font)
        self.label_User1ProjectDescription.setObjectName("label_User1ProjectDescription")
        self.label_Project1Descrip = QtWidgets.QLabel(self.centralwidget)
        self.label_Project1Descrip.setGeometry(QtCore.QRect(30, 170, 311, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_Project1Descrip.setFont(font)
        self.label_Project1Descrip.setObjectName("label_Project1Descrip")
        self.label_User3Name = QtWidgets.QLabel(self.centralwidget)
        self.label_User3Name.setGeometry(QtCore.QRect(670, 480, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_User3Name.setFont(font)
        self.label_User3Name.setObjectName("label_User3Name")
        self.label_Project2ID = QtWidgets.QLabel(self.centralwidget)
        self.label_Project2ID.setGeometry(QtCore.QRect(350, 130, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_Project2ID.setFont(font)
        self.label_Project2ID.setObjectName("label_Project2ID")
        HomePage2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HomePage2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 980, 21))
        self.menubar.setObjectName("menubar")
        HomePage2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HomePage2)
        self.statusbar.setObjectName("statusbar")
        HomePage2.setStatusBar(self.statusbar)
        self.actionProfile = QtWidgets.QAction(HomePage2)
        self.actionProfile.setObjectName("actionProfile")
        self.actionInbox = QtWidgets.QAction(HomePage2)
        self.actionInbox.setObjectName("actionInbox")
        self.actionGroups = QtWidgets.QAction(HomePage2)
        self.actionGroups.setObjectName("actionGroups")

        self.retranslateUi(HomePage2)
        QtCore.QMetaObject.connectSlotsByName(HomePage2)

    def retranslateUi(self, HomePage2):
        _translate = QtCore.QCoreApplication.translate
        HomePage2.setWindowTitle(_translate("HomePage2", "MainWindow"))
        self.pushButton_Logout.setText(_translate("HomePage2", "Logout"))
        self.pushButton_Groups.setText(_translate("HomePage2", "Groups"))
        self.pushButton_Inbox.setText(_translate("HomePage2", "Inbox"))
        self.pushButton_Profile.setText(_translate("HomePage2", "Profile"))
        self.label_AppName.setText(_translate("HomePage2", "TeamUp"))
        self.pushButton_Search.setText(_translate("HomePage2", "Search"))
        self.label_User3ProjectDescription.setText(
            _translate("HomePage2", "Project Description: After school tutoring \n"
                                    "                                 Outdoor cleanup project\n"
                                    "       "))
        self.label_User1Stat.setText(_translate("HomePage2", "User Status: SU"))
        self.label_User2ID.setText(_translate("HomePage2", "User ID: U016"))
        self.label_TopUsers.setText(_translate("HomePage2", "Top Users:"))
        self.label_TopProjects.setText(_translate("HomePage2", "Top Projects:"))
        self.label_User1Name.setText(_translate("HomePage2", "Name: Wilma Mckenzie"))
        self.label_Project2Descrip.setText(_translate("HomePage2", "Project Description: Cleaning parks and \n"
                                                                   "                                nature reserves in the\n"
                                                                   "                                  neighborhood.  \n"
                                                                   " "))
        self.label_User1ID.setText(_translate("HomePage2", "User ID: U005"))
        self.label_Project2Member.setText(_translate("HomePage2", "Team Members: Stan Crossley, \n"
                                                                  "                            Mercedes Cortes,\n"
                                                                  "                           Wilma Mckenzie, \n"
                                                                  "                           Nyah Villanueva  \n"
                                                                  ""))
        self.label_Project1Title.setText(_translate("HomePage2", "Project Title: Pop up library"))
        self.label_User3Score.setText(_translate("HomePage2", "Reputation Score: 16"))
        self.label_User2Stat.setText(_translate("HomePage2", "User Status: VIP"))
        self.label_User3ID.setText(_translate("HomePage2", "User ID: U067"))
        self.label_User2ProjectDescription.setText(_translate("HomePage2", "Project Description: Book and toy drive \n"
                                                                           "                                 Outdoor cleanup project\n"
                                                                           "                                 Document life stories  \n"
                                                                           " "))
        self.label_user1Score.setText(_translate("HomePage2", "Reputation Score: 49"))
        self.label_Project2Title.setText(_translate("HomePage2", "Project Title: Outdoor cleanup project"))
        self.label_User3Stat.setText(_translate("HomePage2", "User Status: OU"))
        self.label_User2Name.setText(_translate("HomePage2", "Name: Nyah Villanueva"))
        self.label_Project1Member.setText(_translate("HomePage2", "Team Members: Rhyley Gamble, \n"
                                                                  "                           Wilma Mckenzie,\n"
                                                                  "                           Rabia Rossi, \n"
                                                                  "                           Olive Sanderson  \n"
                                                                  ""))
        self.label_Project3Member.setText(_translate("HomePage2", "Team Members: Waqas Stuart, \n"
                                                                  "                           Tiya Adams,\n"
                                                                  "                           Rabia Rossi, \n"
                                                                  "                           Nyag Villanueva  \n"
                                                                  ""))
        self.label_Project3Descrip.setText(_translate("HomePage2", "Project Description: Collect donations for \n"
                                                                   "                                local schools and\n"
                                                                   "                                  community centers.  \n"
                                                                   " "))
        self.label_Project3ID.setText(_translate("HomePage2", "Project ID: P007"))
        self.label_User2Score.setText(_translate("HomePage2", "Reputation Score: 31"))
        self.label_Project1ID.setText(_translate("HomePage2", "Project ID: P001"))
        self.label_Project3Title.setText(_translate("HomePage2", "Project Title: Book and toy drive"))
        self.label_User1ProjectDescription.setText(_translate("HomePage2", "Project Description: Pop-up library \n"
                                                                           "                                 Outdoor cleanup project\n"
                                                                           "                                 Document life stories  \n"
                                                                           " "))
        self.label_Project1Descrip.setText(_translate("HomePage2", "Project Description: Build a pop-up library \n"
                                                                   "                                and invite the community\n"
                                                                   "                                  to donate and take books.  \n"
                                                                   " "))
        self.label_User3Name.setText(_translate("HomePage2", "Name: Stan Crossley"))
        self.label_Project2ID.setText(_translate("HomePage2", "Project ID: P004"))
        self.actionProfile.setText(_translate("HomePage2", "Profile"))
        self.actionInbox.setText(_translate("HomePage2", "Inbox"))
        self.actionGroups.setText(_translate("HomePage2", "Groups"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    HomePage2 = QtWidgets.QMainWindow()
    ui = Ui_HomePage2()
    ui.setupUi(HomePage2)
    HomePage2.show()
    sys.exit(app.exec_())
