# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomePage2.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 50, 981, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 70, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_User3 = QtWidgets.QLabel(self.centralwidget)
        self.label_User3.setGeometry(QtCore.QRect(640, 420, 281, 251))
        self.label_User3.setObjectName("label_User3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(490, 430, 54, 12))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_Project3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Project3.setGeometry(QtCore.QRect(660, 120, 271, 251))
        self.label_Project3.setObjectName("label_Project3")
        self.label_Project1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Project1.setGeometry(QtCore.QRect(30, 120, 281, 251))
        self.label_Project1.setObjectName("label_Project1")
        self.label_AppName = QtWidgets.QLabel(self.centralwidget)
        self.label_AppName.setGeometry(QtCore.QRect(410, 10, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_AppName.setFont(font)
        self.label_AppName.setObjectName("label_AppName")
        self.label_Project2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Project2.setGeometry(QtCore.QRect(350, 120, 271, 251))
        self.label_Project2.setObjectName("label_Project2")
        self.label_User2 = QtWidgets.QLabel(self.centralwidget)
        self.label_User2.setGeometry(QtCore.QRect(330, 420, 281, 251))
        self.label_User2.setObjectName("label_User2")
        self.label_User1 = QtWidgets.QLabel(self.centralwidget)
        self.label_User1.setGeometry(QtCore.QRect(20, 430, 281, 251))
        self.label_User1.setObjectName("label_User1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 390, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 980, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuLogout = QtWidgets.QMenu(self.menubar)
        self.menuLogout.setObjectName("menuLogout")
        self.menuLogout_2 = QtWidgets.QMenu(self.menubar)
        self.menuLogout_2.setObjectName("menuLogout_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionProfile = QtWidgets.QAction(MainWindow)
        self.actionProfile.setObjectName("actionProfile")
        self.actionInbox = QtWidgets.QAction(MainWindow)
        self.actionInbox.setObjectName("actionInbox")
        self.actionGroups = QtWidgets.QAction(MainWindow)
        self.actionGroups.setObjectName("actionGroups")
        self.menuMenu.addAction(self.actionProfile)
        self.menuMenu.addAction(self.actionInbox)
        self.menuMenu.addAction(self.actionGroups)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuLogout.menuAction())
        self.menubar.addAction(self.menuLogout_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Top Projects:"))
        self.label_User3.setText(_translate("MainWindow", "TextLabel"))
        self.label_Project3.setText(_translate("MainWindow", "TextLabel"))
        self.label_Project1.setText(_translate("MainWindow", "TextLabel"))
        self.label_AppName.setText(_translate("MainWindow", "AppName"))
        self.label_Project2.setText(_translate("MainWindow", "TextLabel"))
        self.label_User2.setText(_translate("MainWindow", "TextLabel"))
        self.label_User1.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Top User:"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuLogout.setTitle(_translate("MainWindow", "Search"))
        self.menuLogout_2.setTitle(_translate("MainWindow", "Logout"))
        self.actionProfile.setText(_translate("MainWindow", "Profile"))
        self.actionInbox.setText(_translate("MainWindow", "Inbox"))
        self.actionGroups.setText(_translate("MainWindow", "Groups"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
