from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_registrationPage(object):
    def submit(self):
        # pop up window
        msg = QMessageBox()
        msg.setWindowTitle("Registration Status")
        msg.setText("Registration form submitted!")
        x = msg.exec_()

        # record data in to db

    def setupUi(self, registrationPage):
        registrationPage.setObjectName("registrationPage")
        registrationPage.resize(468, 719)
        self.centralwidget = QtWidgets.QWidget(registrationPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(20, 30, 54, 12))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.label_email = QtWidgets.QLabel(self.centralwidget)
        self.label_email.setGeometry(QtCore.QRect(20, 80, 54, 12))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.label_references = QtWidgets.QLabel(self.centralwidget)
        self.label_references.setGeometry(QtCore.QRect(20, 130, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_references.setFont(font)
        self.label_references.setObjectName("label_references")
        self.label_interests = QtWidgets.QLabel(self.centralwidget)
        self.label_interests.setGeometry(QtCore.QRect(20, 220, 54, 12))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_interests.setFont(font)
        self.label_interests.setObjectName("label_interests")
        self.label_skills = QtWidgets.QLabel(self.centralwidget)
        self.label_skills.setGeometry(QtCore.QRect(20, 280, 54, 12))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_skills.setFont(font)
        self.label_skills.setObjectName("label_skills")
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(20, 360, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(20, 410, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.label_additional = QtWidgets.QLabel(self.centralwidget)
        self.label_additional.setGeometry(QtCore.QRect(20, 470, 54, 12))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_additional.setFont(font)
        self.label_additional.setObjectName("label_additional")
        self.pushButton_submit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_submit.setGeometry(QtCore.QRect(180, 600, 111, 51))

        self.pushButton_submit.clicked.connect(self.submit) # connect button to pop up window function

        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_submit.setFont(font)
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.checkBox_interest2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest2.setGeometry(QtCore.QRect(170, 220, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_interest2.setFont(font)
        self.checkBox_interest2.setObjectName("checkBox_interest2")
        self.checkBox_interest1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest1.setGeometry(QtCore.QRect(80, 220, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_interest1.setFont(font)
        self.checkBox_interest1.setObjectName("checkBox_interest1")
        self.checkBox_skill1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_skill1.setGeometry(QtCore.QRect(80, 280, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_skill1.setFont(font)
        self.checkBox_skill1.setObjectName("checkBox_skill1")
        self.checkBox_interest3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest3.setGeometry(QtCore.QRect(260, 220, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_interest3.setFont(font)
        self.checkBox_interest3.setObjectName("checkBox_interest3")
        self.checkBox_interest4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest4.setGeometry(QtCore.QRect(350, 220, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_interest4.setFont(font)
        self.checkBox_interest4.setObjectName("checkBox_interest4")
        self.checkBox_interest5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest5.setGeometry(QtCore.QRect(80, 250, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_interest5.setFont(font)
        self.checkBox_interest5.setObjectName("checkBox_interest5")
        self.checkBox_interest6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest6.setGeometry(QtCore.QRect(170, 250, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_interest6.setFont(font)
        self.checkBox_interest6.setObjectName("checkBox_interest6")
        self.checkBox_interest7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest7.setGeometry(QtCore.QRect(260, 250, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_interest7.setFont(font)
        self.checkBox_interest7.setObjectName("checkBox_interest7")
        self.checkBox_interest8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest8.setGeometry(QtCore.QRect(350, 250, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_interest8.setFont(font)
        self.checkBox_interest8.setObjectName("checkBox_interest8")
        self.checkBox_skill2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_skill2.setGeometry(QtCore.QRect(170, 280, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_skill2.setFont(font)
        self.checkBox_skill2.setObjectName("checkBox_skill2")
        self.checkBox_skill5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_skill5.setGeometry(QtCore.QRect(80, 310, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_skill5.setFont(font)
        self.checkBox_skill5.setObjectName("checkBox_skill5")
        self.checkBox_skill3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_skill3.setGeometry(QtCore.QRect(260, 280, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_skill3.setFont(font)
        self.checkBox_skill3.setObjectName("checkBox_skill3")
        self.checkBox_skill6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_skill6.setGeometry(QtCore.QRect(190, 310, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_skill6.setFont(font)
        self.checkBox_skill6.setObjectName("checkBox_skill6")
        self.checkBox_skill4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_skill4.setGeometry(QtCore.QRect(350, 280, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_skill4.setFont(font)
        self.checkBox_skill4.setObjectName("checkBox_skill4")
        self.checkBox_skill7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_skill7.setGeometry(QtCore.QRect(310, 310, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_skill7.setFont(font)
        self.checkBox_skill7.setObjectName("checkBox_skill7")
        self.textEdit_name = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_name.setGeometry(QtCore.QRect(110, 20, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textEdit_name.setFont(font)
        self.textEdit_name.setObjectName("textEdit_name")
        self.textEdit_email = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_email.setGeometry(QtCore.QRect(110, 70, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textEdit_email.setFont(font)
        self.textEdit_email.setObjectName("textEdit_email")
        self.textEdit_reference1 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_reference1.setGeometry(QtCore.QRect(110, 120, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textEdit_reference1.setFont(font)
        self.textEdit_reference1.setObjectName("textEdit_reference1")
        self.textEdit_username = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_username.setGeometry(QtCore.QRect(110, 360, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textEdit_username.setFont(font)
        self.textEdit_username.setObjectName("textEdit_username")
        self.textEdit_password = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_password.setGeometry(QtCore.QRect(110, 410, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textEdit_password.setFont(font)
        self.textEdit_password.setObjectName("textEdit_password")
        self.textEdit_additionalInfo = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_additionalInfo.setGeometry(QtCore.QRect(110, 470, 281, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textEdit_additionalInfo.setFont(font)
        self.textEdit_additionalInfo.setObjectName("textEdit_additionalInfo")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(20, 490, 54, 12))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_info.setFont(font)
        self.label_info.setObjectName("label_info")
        self.textEdit_reference2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_reference2.setGeometry(QtCore.QRect(110, 160, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textEdit_reference2.setFont(font)
        self.textEdit_reference2.setObjectName("textEdit_reference2")
        registrationPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(registrationPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 468, 21))
        self.menubar.setObjectName("menubar")
        registrationPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(registrationPage)
        self.statusbar.setObjectName("statusbar")
        registrationPage.setStatusBar(self.statusbar)

        self.retranslateUi(registrationPage)
        QtCore.QMetaObject.connectSlotsByName(registrationPage)

    def retranslateUi(self, registrationPage):
        _translate = QtCore.QCoreApplication.translate
        registrationPage.setWindowTitle(_translate("registrationPage", "MainWindow"))
        self.label_name.setText(_translate("registrationPage", "Name:"))
        self.label_email.setText(_translate("registrationPage", "Email:"))
        self.label_references.setText(_translate("registrationPage", "References:"))
        self.label_interests.setText(_translate("registrationPage", "Interests:"))
        self.label_skills.setText(_translate("registrationPage", "Skill sets:"))
        self.label_username.setText(_translate("registrationPage", "Username:"))
        self.label_password.setText(_translate("registrationPage", "Password:"))
        self.label_additional.setText(_translate("registrationPage", "Additional"))
        self.pushButton_submit.setText(_translate("registrationPage", "Submit"))
        self.checkBox_interest2.setText(_translate("registrationPage", "Reading"))
        self.checkBox_interest1.setText(_translate("registrationPage", "Education"))
        self.checkBox_skill1.setText(_translate("registrationPage", "Organizing"))
        self.checkBox_interest3.setText(_translate("registrationPage", "Coding"))
        self.checkBox_interest4.setText(_translate("registrationPage", "Environment"))
        self.checkBox_interest5.setText(_translate("registrationPage", "Sports"))
        self.checkBox_interest6.setText(_translate("registrationPage", "Design"))
        self.checkBox_interest7.setText(_translate("registrationPage", "Finance"))
        self.checkBox_interest8.setText(_translate("registrationPage", "Techology"))
        self.checkBox_skill2.setText(_translate("registrationPage", "Python"))
        self.checkBox_skill5.setText(_translate("registrationPage", "Presentation"))
        self.checkBox_skill3.setText(_translate("registrationPage", "Java"))
        self.checkBox_skill6.setText(_translate("registrationPage", "Graphic Design"))
        self.checkBox_skill4.setText(_translate("registrationPage", "Excel"))
        self.checkBox_skill7.setText(_translate("registrationPage", "Accounting"))
        self.label_info.setText(_translate("registrationPage", "Info:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registrationPage = QtWidgets.QMainWindow()
    ui = Ui_registrationPage()
    ui.setupUi(registrationPage)
    registrationPage.show()
    sys.exit(app.exec_())
