# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegistrationPage.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(463, 491)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(20, 20, 54, 12))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.label_email = QtWidgets.QLabel(self.centralwidget)
        self.label_email.setGeometry(QtCore.QRect(20, 60, 54, 12))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.label_reference = QtWidgets.QLabel(self.centralwidget)
        self.label_reference.setGeometry(QtCore.QRect(20, 100, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_reference.setFont(font)
        self.label_reference.setObjectName("label_reference")
        self.label_inerest = QtWidgets.QLabel(self.centralwidget)
        self.label_inerest.setGeometry(QtCore.QRect(20, 140, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_inerest.setFont(font)
        self.label_inerest.setObjectName("label_inerest")
        self.label_skill = QtWidgets.QLabel(self.centralwidget)
        self.label_skill.setGeometry(QtCore.QRect(20, 210, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_skill.setFont(font)
        self.label_skill.setObjectName("label_skill")
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(20, 280, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(20, 330, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.textEdit_name = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_name.setGeometry(QtCore.QRect(70, 10, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textEdit_name.setFont(font)
        self.textEdit_name.setObjectName("textEdit_name")
        self.textEdit_email = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_email.setGeometry(QtCore.QRect(70, 50, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textEdit_email.setFont(font)
        self.textEdit_email.setObjectName("textEdit_email")
        self.textEdit_reference = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_reference.setGeometry(QtCore.QRect(100, 90, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textEdit_reference.setFont(font)
        self.textEdit_reference.setObjectName("textEdit_reference")
        self.checkBox_interest1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest1.setGeometry(QtCore.QRect(80, 140, 81, 16))
        self.checkBox_interest1.setObjectName("checkBox_interest1")
        self.checkBox_interest2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest2.setGeometry(QtCore.QRect(170, 140, 91, 16))
        self.checkBox_interest2.setObjectName("checkBox_interest2")
        self.checkBox_interest3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest3.setGeometry(QtCore.QRect(260, 140, 71, 16))
        self.checkBox_interest3.setObjectName("checkBox_interest3")
        self.checkBox_interest4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest4.setGeometry(QtCore.QRect(340, 140, 101, 16))
        self.checkBox_interest4.setObjectName("checkBox_interest4")
        self.checkBox_interest5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest5.setGeometry(QtCore.QRect(80, 170, 81, 16))
        self.checkBox_interest5.setObjectName("checkBox_interest5")
        self.checkBox_interest6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest6.setGeometry(QtCore.QRect(170, 170, 81, 16))
        self.checkBox_interest6.setObjectName("checkBox_interest6")
        self.checkBox_interest7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest7.setGeometry(QtCore.QRect(260, 170, 81, 16))
        self.checkBox_interest7.setObjectName("checkBox_interest7")
        self.checkBox_interest8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest8.setGeometry(QtCore.QRect(340, 170, 91, 16))
        self.checkBox_interest8.setObjectName("checkBox_interest8")
        self.checkBox_skill4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_skill4.setGeometry(QtCore.QRect(320, 240, 81, 16))
        self.checkBox_skill4.setObjectName("checkBox_skill4")
        self.checkBox_skill5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_skill5.setGeometry(QtCore.QRect(80, 240, 111, 16))
        self.checkBox_skill5.setObjectName("checkBox_skill5")
        self.checkBox_skill3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_skill3.setGeometry(QtCore.QRect(260, 210, 71, 16))
        self.checkBox_skill3.setObjectName("checkBox_skill3")
        self.checkBox_skill1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_skill1.setGeometry(QtCore.QRect(80, 210, 71, 16))
        self.checkBox_skill1.setObjectName("checkBox_skill1")
        self.checkBox_skill7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_skill7.setGeometry(QtCore.QRect(200, 240, 121, 16))
        self.checkBox_skill7.setObjectName("checkBox_skill7")
        self.checkBox_skill2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_skill2.setGeometry(QtCore.QRect(170, 210, 71, 16))
        self.checkBox_skill2.setObjectName("checkBox_skill2")
        self.textEdit_username = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_username.setGeometry(QtCore.QRect(90, 270, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textEdit_username.setFont(font)
        self.textEdit_username.setObjectName("textEdit_username")
        self.textEdit_password = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_password.setGeometry(QtCore.QRect(90, 320, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textEdit_password.setFont(font)
        self.textEdit_password.setObjectName("textEdit_password")
        self.pushButton_submit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_submit.setGeometry(QtCore.QRect(160, 380, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_submit.setFont(font)
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.checkBox_interest8_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interest8_2.setGeometry(QtCore.QRect(350, 210, 91, 16))
        self.checkBox_interest8_2.setObjectName("checkBox_interest8_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 463, 21))
        self.menubar.setObjectName("menubar")
        self.menuback = QtWidgets.QMenu(self.menubar)
        self.menuback.setObjectName("menuback")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuback.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name.setText(_translate("MainWindow", "Name:"))
        self.label_email.setText(_translate("MainWindow", "Email:"))
        self.label_reference.setText(_translate("MainWindow", "Reference:"))
        self.label_inerest.setText(_translate("MainWindow", "Interest:"))
        self.label_skill.setText(_translate("MainWindow", "Skill sets:"))
        self.label_username.setText(_translate("MainWindow", "Username:"))
        self.label_password.setText(_translate("MainWindow", "Password:"))
        self.checkBox_interest1.setText(_translate("MainWindow", "Education"))
        self.checkBox_interest2.setText(_translate("MainWindow", "Mangement"))
        self.checkBox_interest3.setText(_translate("MainWindow", "Coding"))
        self.checkBox_interest4.setText(_translate("MainWindow", "Communication"))
        self.checkBox_interest5.setText(_translate("MainWindow", "On-field"))
        self.checkBox_interest6.setText(_translate("MainWindow", "Design"))
        self.checkBox_interest7.setText(_translate("MainWindow", "Finance"))
        self.checkBox_interest8.setText(_translate("MainWindow", "Techology"))
        self.checkBox_skill4.setText(_translate("MainWindow", "Database "))
        self.checkBox_skill5.setText(_translate("MainWindow", "Data analsysis"))
        self.checkBox_skill3.setText(_translate("MainWindow", "Java"))
        self.checkBox_skill1.setText(_translate("MainWindow", "C++"))
        self.checkBox_skill7.setText(_translate("MainWindow", "GUI development"))
        self.checkBox_skill2.setText(_translate("MainWindow", "Python"))
        self.pushButton_submit.setText(_translate("MainWindow", "Submit"))
        self.checkBox_interest8_2.setText(_translate("MainWindow", "Excel"))
        self.menuback.setTitle(_translate("MainWindow", "back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
