from PyQt5 import QtCore, QtGui, QtWidgets
from ProfilePage import Ui_profilePage




class Ui_GroupPage(object):
    def logout(self):
        MainWindow.close()

    def openInboxPage(self):
        from InboxPage import Ui_InboxPage
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_InboxPage()
        self.ui.setupUi(self.window)
        self.window.show()


    def openLoginWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_loginPage()
        self.ui.setupUi(self.window)
        self.window.show()

    def openProfileWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_profilePage()
        self.ui.setupUi(self.window)
        self.window.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1234, 846)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NavigationSideBar = QtWidgets.QGroupBox(self.centralwidget)
        self.NavigationSideBar.setGeometry(QtCore.QRect(760, 0, 451, 61))
        self.NavigationSideBar.setObjectName("NavigationSideBar")
        self.InboxButton = QtWidgets.QPushButton(self.NavigationSideBar)
        self.InboxButton.setGeometry(QtCore.QRect(120, 20, 101, 28))
        self.InboxButton.setObjectName("InboxButton")
        self.InboxButton.clicked.connect(self.openInboxPage)
        self.InboxButton.clicked.connect(MainWindow.close)
        self.ProfileButton = QtWidgets.QPushButton(self.NavigationSideBar)
        self.ProfileButton.setGeometry(QtCore.QRect(10, 20, 101, 28))
        self.ProfileButton.setObjectName("ProfileButton")
        self.ProfileButton.clicked.connect(self.openProfileWindow)

        self.LogOUt = QtWidgets.QPushButton(self.NavigationSideBar)
        self.LogOUt.setGeometry(QtCore.QRect(340, 20, 101, 28))
        self.LogOUt.setObjectName("LogOUt")
        self.GroupsButton = QtWidgets.QPushButton(self.NavigationSideBar)
        self.GroupsButton.setGeometry(QtCore.QRect(230, 20, 101, 28))
        self.GroupsButton.setObjectName("GroupsButton")
        self.Dashboard = QtWidgets.QScrollArea(self.centralwidget)
        self.Dashboard.setGeometry(QtCore.QRect(230, 80, 751, 661))
        self.Dashboard.setWidgetResizable(True)
        self.Dashboard.setObjectName("Dashboard")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 749, 659))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.MeetUpPoll = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.MeetUpPoll.setGeometry(QtCore.QRect(10, 240, 701, 91))
        self.MeetUpPoll.setObjectName("MeetUpPoll")
        self.Choice1 = QtWidgets.QCheckBox(self.MeetUpPoll)
        self.Choice1.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.Choice1.setObjectName("Choice1")
        self.SubmitVote = QtWidgets.QPushButton(self.MeetUpPoll)
        self.SubmitVote.setGeometry(QtCore.QRect(590, 60, 93, 28))
        self.SubmitVote.setObjectName("SubmitVote")
        self.Choice2 = QtWidgets.QCheckBox(self.MeetUpPoll)
        self.Choice2.setGeometry(QtCore.QRect(10, 50, 101, 20))
        self.Choice2.setObjectName("Choice2")
        self.Choice3 = QtWidgets.QCheckBox(self.MeetUpPoll)
        self.Choice3.setGeometry(QtCore.QRect(160, 20, 131, 20))
        self.Choice3.setObjectName("Choice3")
        self.Choice4 = QtWidgets.QCheckBox(self.MeetUpPoll)
        self.Choice4.setGeometry(QtCore.QRect(160, 50, 131, 20))
        self.Choice4.setObjectName("Choice4")
        self.Choice5 = QtWidgets.QCheckBox(self.MeetUpPoll)
        self.Choice5.setGeometry(QtCore.QRect(320, 20, 101, 20))
        self.Choice5.setObjectName("Choice5")
        self.GroupPost = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.GroupPost.setGeometry(QtCore.QRect(10, 10, 701, 221))
        self.GroupPost.setObjectName("GroupPost")
        self.PostText = QtWidgets.QTextBrowser(self.GroupPost)
        self.PostText.setGeometry(QtCore.QRect(10, 20, 681, 111))
        self.PostText.setObjectName("PostText")
        self.textEdit_2 = QtWidgets.QTextEdit(self.GroupPost)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 140, 681, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.GroupPost)
        self.pushButton.setGeometry(QtCore.QRect(590, 180, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.VoteWarning = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.VoteWarning.setGeometry(QtCore.QRect(10, 340, 701, 91))
        self.VoteWarning.setObjectName("VoteWarning")
        self.YesBox = QtWidgets.QCheckBox(self.VoteWarning)
        self.YesBox.setGeometry(QtCore.QRect(10, 30, 81, 20))
        self.YesBox.setObjectName("YesBox")
        self.NoBox = QtWidgets.QCheckBox(self.VoteWarning)
        self.NoBox.setGeometry(QtCore.QRect(10, 60, 81, 20))
        self.NoBox.setObjectName("NoBox")
        self.SubmitVote_2 = QtWidgets.QPushButton(self.VoteWarning)
        self.SubmitVote_2.setGeometry(QtCore.QRect(590, 60, 93, 28))
        self.SubmitVote_2.setObjectName("SubmitVote_2")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(730, 0, 16, 160))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.Dashboard.setWidget(self.scrollAreaWidgetContents)
        self.GroupCommands = QtWidgets.QGroupBox(self.centralwidget)
        self.GroupCommands.setGeometry(QtCore.QRect(990, 70, 221, 271))
        self.GroupCommands.setObjectName("GroupCommands")
        self.Leave_Group_2 = QtWidgets.QPushButton(self.GroupCommands)
        self.Leave_Group_2.setGeometry(QtCore.QRect(0, 240, 221, 28))
        self.Leave_Group_2.setObjectName("Leave_Group_2")
        self.CreatePost = QtWidgets.QPushButton(self.GroupCommands)
        self.CreatePost.setGeometry(QtCore.QRect(0, 20, 221, 28))
        self.CreatePost.setObjectName("CreatePost")
        self.CreateMeetUpPoll = QtWidgets.QPushButton(self.GroupCommands)
        self.CreateMeetUpPoll.setGeometry(QtCore.QRect(0, 50, 221, 28))
        self.CreateMeetUpPoll.setObjectName("CreateMeetUpPoll")
        self.CreateMemberPoll = QtWidgets.QPushButton(self.GroupCommands)
        self.CreateMemberPoll.setGeometry(QtCore.QRect(0, 80, 221, 28))
        self.CreateMemberPoll.setObjectName("CreateMemberPoll")
        self.CreateMemberPoll_2 = QtWidgets.QPushButton(self.GroupCommands)
        self.CreateMemberPoll_2.setGeometry(QtCore.QRect(0, 110, 221, 28))
        self.CreateMemberPoll_2.setObjectName("CreateMemberPoll_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 211, 271))
        self.groupBox.setObjectName("groupBox")
        self.GroupNotificationsList = QtWidgets.QListView(self.groupBox)
        self.GroupNotificationsList.setGeometry(QtCore.QRect(10, 20, 191, 241))
        self.GroupNotificationsList.setObjectName("GroupNotificationsList")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 211, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.textEdit.setObjectName("textEdit")
        self.HomeButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.HomeButton_2.setGeometry(QtCore.QRect(140, 20, 61, 31))
        self.HomeButton_2.setObjectName("HomeButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1234, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NavigationSideBar.setTitle(_translate("MainWindow", "Navigation"))
        self.InboxButton.setText(_translate("MainWindow", "Inbox"))
        self.ProfileButton.setText(_translate("MainWindow", "Profile"))
        self.LogOUt.setText(_translate("MainWindow", "LogOut"))
        self.GroupsButton.setText(_translate("MainWindow", "Groups"))
        self.MeetUpPoll.setTitle(_translate("MainWindow", "Poll"))
        self.Choice1.setText(_translate("MainWindow", "Tuesday 2pm"))
        self.SubmitVote.setText(_translate("MainWindow", "Submit"))
        self.Choice2.setText(_translate("MainWindow", "Tuesday 7pm"))
        self.Choice3.setText(_translate("MainWindow", "Thursday 1pm"))
        self.Choice4.setText(_translate("MainWindow", "Saturday 3pm"))
        self.Choice5.setText(_translate("MainWindow", "Sunday 2pm"))
        self.GroupPost.setTitle(_translate("MainWindow", "Post"))
        self.PostText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">This is a group post</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Comment"))
        self.VoteWarning.setTitle(_translate("MainWindow", "Vote to Send Warning/Compliment to [USER NAME]"))
        self.YesBox.setText(_translate("MainWindow", "Yes"))
        self.NoBox.setText(_translate("MainWindow", "No"))
        self.SubmitVote_2.setText(_translate("MainWindow", "Submit"))
        self.GroupCommands.setTitle(_translate("MainWindow", "GroupBox"))
        self.Leave_Group_2.setText(_translate("MainWindow", "Leave Group"))
        self.CreatePost.setText(_translate("MainWindow", "Create Post"))
        self.CreateMeetUpPoll.setText(_translate("MainWindow", "Create Meet Up Poll"))
        self.CreateMemberPoll.setText(_translate("MainWindow", "Create Member Poll"))
        self.CreateMemberPoll_2.setText(_translate("MainWindow", "Group Info"))
        self.groupBox.setTitle(_translate("MainWindow", "Community Garden Notifications:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Search"))
        self.HomeButton_2.setText(_translate("MainWindow", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_GroupPage()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
